### ISSUE TITLE
Support any file type

### ISSUE THREAD

**Issue by jvisser** [sapegin/grunt-bower-concat#40]
Make it possible to support any file type for example:

filetypes: {
"css" : "dist/main.css",
"js" : "dist/main.js",
"scss" : "src/sass/_bowerdeps.scss"
}

Possibly make the key a regex for file matching.

And not exit with an error when main files of a specific type are not found in a module as happens in the the current version (or add a force option and make it a warning instead of an error that fails the build).

**Comment by sapegin** [comment]
1. Good idea for pull request.

2. I don’t think that it’s good idea. You have to either define main files manually or excllude those packages.

**Comment by jvisser** [comment]
I mentioned the no main files error because I think it is related. I agree with you that no main files specified at all in the bower component should throw an error. 

But in the case where you there are main files specified but they don't match the file type filter it should at most give a warning imo. This is at this time already a problem for example with bower components that specifiy non css/js files as main (this fails the build because bower_concat cannot find main files for css/js).

**Comment by sapegin** [comment]
You’re right. It’s obviously a bug.
