### ISSUE TITLE
Font Awesome Doesn't Work

### ISSUE THREAD

**Issue by JaredCubilla** [sapegin/grunt-bower-concat#44]
When I use this tool for concatenating Font Awesome's css with the other CSS Bower Packages I've downloaded, it returns an error saying that it could not access the Font Awesome font itself, because it takes the CSS out of it's directory, and the webfont is left behind.

Is there a way I could fix this?

**Comment by sapegin** [comment]
You probably think that I can read your mind. I can’t.

Show me your gruntfile and bower.json (at least) and I could try to help yo.
