### ISSUE TITLE
task should only be run if needed

### ISSUE THREAD

**Issue by PhilippSoehnlein** [sapegin/grunt-bower-concat#51]
The ``bower_concat`` task is always executed, even if nothing changed in the ``bower_components`` directory. To speed up builds it would be nice, if the task checks if the dest file is older than the newest file in ``bower_components``.

This could be achieved easily if grunt-bower-concat would play nice together with <a href="https://www.npmjs.com/package/grunt-newer">grunt-newer</a>, but it isn't, because grunt-newer would call grunt-bower-concat with an object like ``{ files: [ { src: [Object], dest: 'build/vendor.js', orig: [Object] } ] }`` instead of the awaited object like ``{ dest: 'build/tmp/vendor.js' }``.

Here's an example config with grunt-newer:
```js
grunt.initConfig( {
    bower_concat: {
        build: {
            dest: 'build/vendor.js',
        }
    },
    concat: {
        build: {
            src: [ 'build/vendor.js', 'src/app.js' ]
            dest: 'build/all.js',
        }
    },
    uglify: {
        build: {
            files: {
                'build/main.min.js': [ 'build/main.js' ],
            },
        },
    },
} );

grunt.loadNpmTasks( 'grunt-bower-concat' );
grunt.loadNpmTasks( 'grunt-contrib-uglify' );
grunt.loadNpmTasks( 'grunt-newer' );

grunt.registerTask( 'build:js', [
    'newer:bower_concat:build', // concat all third party dependencies
    'concat:build',             // concat third party stuff and our own JS
    'uglify:build',             // minify everything
] );
```

**Comment by sapegin** [comment]
It’s a very old bug in grunt-newer: https://github.com/tschaub/grunt-newer/issues/45.
