### ISSUE TITLE
mainFiles() seems to be ignored

### ISSUE THREAD

**Issue by Nickvda** [sapegin/grunt-bower-concat#58]
Greetings,

I have got bower_concat up and running for the most part- but the one thing that I just can't seem to get to work is the mainFiles() option. I have tried placing the options in different orders, tried the various ways of adding the files in it, but to no avail. Have tried multiple plugins and files, but it doesn't seem to help.

I have supplied my Gruntfile over at Stackoverflow: http://stackoverflow.com/questions/32946688/grunt-grunt-bower-concat-ignoring-mainfiles-option

Is this just me being a noob, or..?

**Comment by sapegin** [comment]
Try to run grunt with `--verbose` option. And you don’t need to write `bower_components/bootstrap/` like in the docs: https://github.com/sapegin/grunt-bower-concat#mainfiles.

**Comment by Nickvda** [comment]
Thanks on both points, that was it!

Thankfully it was just me being nooby :)
