### ISSUE TITLE
Correct way to handle modules with missing end semicolon

### ISSUE THREAD

**Issue by jthrilly** [sapegin/grunt-bower-concat#60]
What is the correct way to deal with a module that doesn't end with a semi-colon? mapbox.js doesn't have one in either the source or minified versions it distributes, which causes whatever follows to throw 'cannot find module' exception with bower_concat.

It seems like they simply advise people with problems to 'use better build tools'.

**Comment by sapegin** [comment]
The correct way is to fix the improperly built library.

If they don’t want to that you can try to use the [separator](https://github.com/sapegin/grunt-bower-concat#separator) option.

**Comment by jthrilly** [comment]
Thanks. FWIW I agree completely, but they are adamant that they are in the right. I'm not sure I know enough to comment on the technical arguments, but it seems very petty since a number of users have raised this issue.
